name: Compile C Programs

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile all C files
        run: |
          gcc -Wall -o main *.c || true
